language: cpp

compiler:
    - clang
    - gcc

addons:
  apt:
    sources:
      - george-edison55/cmake-3.x #cmake 3.2
      - ubuntu-toolchain-r-test #g++
      - llvm-toolchain-precise-3.4 #clang
    packages:
      - g++-4.9
      - llvm-3.4-dev
      - clang-3.4


before_install:
    - sudo apt-get update -qq

install:
    # cmake 3.2
    - sudo apt-get install cmake cmake-data

    # g++4.9
    - if [ "$CXX" == "g++" ]; then export CXX="g++-4.9"; fi

    # clang 3.4
    - if [ "$CXX" == "clang++" ]; then export CXX=clang++-3.4 && travis/install_libcxx.sh; fi

script:
    - mkdir build
    - cd build
    - cmake ..
    - make
