language: cpp

compiler:
    - gcc


before_install:
    #cmake 3.2
    - sudo add-apt-repository ppa:george-edison55/cmake-3.x -y

    # g++
    - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi

    - sudo apt-get update -qq


install:
    # cmake 3.2
    - sudo apt-get install cmake cmake-data

    # g++4.9
    - if [ "$CXX" == "g++" ]; then sudo apt-get install -qq g++-4.9; fi
    - if [ "$CXX" == "g++" ]; then export CXX="g++-4.9"; fi

    #gflags for glog
    -  sudo apt-get install libgflags-dev


script:
    - mkdir build
    - cd build
    - cmake ..
    - make
